#!/usr/bin/env node

const {
	init,
	addCommands,
	close,
} = require('@builderx-framework/core/helpers/commander');

const start = async () => {
	// initialise the commander
	await init();

	// register commands to the commander
	await addCommands();

	// close commander
	await close();
};

start();
